//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question
    {
        public int ID { get; set; }
        public string QuesTitle { get; set; }
        public string QuesDesc { get; set; }
        public string QuesIMG { get; set; }
        public string QuesLink { get; set; }
        public Nullable<bool> IsHiden { get; set; }
        public Nullable<int> QuesPosition { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
